---
title: "Ejemplo 3"
author: "Guillermo Durán G"
format: pptx
editor: visual
---

## Ejemplo 3

Un camión para el transporte de electrodomésticos cobra 25 euros por cada frigorífico de 0,6 m2
de base y 22 euros por cada lavavajillas de 0,5 m2 de base.

El camión dispone de 9 m2 como máximo para este tipo de carga. Por necesidades de demanda el número de lavavajillas no puede superar al 60% del número de frigoríficos. Se deben transportar como mínimo 5 frigoríficos.

1\) Gráfica la región factible.

2\) Determina el número de electrodomésticos de cada clase para que el beneficio obtenido con el transporte sea lo más grande posible.

3\) Calcula el beneficio máximo.

## Solución

Sean x = número de frigoríficos, y = número de lavavajillas.
Función objetivo: f (x,y)=25x+22y
Restricciones:
*x , y≥0
0,6 x+0,5 y≤9
y≤0,6 x
x≥5*

## Code

When you click the **Render** button a presentation will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```
